### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ngxson** [csutorasa/XOutput#187]
Hi, you can find some debug information here:

```
2020-09-09 21:52:11.627 +02:00 INFO  XOutput.Tools.DependencyEmbedder.CurrentDomain_AssemblyResolve: Loading SharpDX.DirectInput.dll from embedded resources
2020-09-09 21:52:11.656 +02:00 INFO  XOutput.Tools.DependencyEmbedder.CurrentDomain_AssemblyResolve: Loading SharpDX.dll from embedded resources
2020-09-09 21:52:11.690 +02:00 ERROR XOutput.App.Application_Startup: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> SharpDX.SharpDXException: HRESULT: [0x80004005], Module: [General], ApiCode: [E_FAIL/Unspecified error], Message: Unspecified error

   at SharpDX.Result.CheckError()
   at SharpDX.DirectInput.DirectInput..ctor()
   at XOutput.UI.Windows.MainWindowViewModel..ctor(MainWindowModel model, Dispatcher dispatcher, HidGuardianManager hidGuardianManager)
   at XOutput.UI.UIConfiguration.GetMainWindowViewModel(MainWindowModel model, Dispatcher dispatcher, HidGuardianManager hidGuardianManager)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at XOutput.Tools.Resolver.Create(Object[] values)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at XOutput.Tools.ApplicationContext.Resolve(Type type)
   at XOutput.Tools.ApplicationContext.Resolve[T]()
   at XOutput.App.Application_Startup(Object sender, StartupEventArgs e)

```

![image](https://user-images.githubusercontent.com/7702203/92647012-86bb2400-f2e7-11ea-83f7-20469e7a7977.png)

**Comment by ngxson** [comment]
Close because it's actually a problem due to Windows 10 19041 update
