### ISSUE TITLE
Seems to crash on launch even with ViGEm installed

### ISSUE THREAD

**Issue by totallymagical** [csutorasa/XOutput#42]
I've been trying to open XOutput but it freezes and then crashes after a few seconds. I have both ViGEm and ScpToolkit, I've tried restarting after installing both and adding and removing ViGEm buses multiple times.
This is the log

`2018-04-28 23:49:27.939 -05:00 INFO  LanguageManager.set_Language: Language is set to English
2018-04-28 23:49:27.955 -05:00 INFO  MainWindowViewModel.Initialize: Loading settings was successful.
2018-04-28 23:49:27.970 -05:00 ERROR MainWindowViewModel.UnhandledException: System.DllNotFoundException: Unable to load DLL 'vigemclient.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Nefarius.ViGEm.Client.ViGEmClient.vigem_alloc()
   at Nefarius.ViGEm.Client.ViGEmClient..ctor()
   at XOutput.Devices.XInput.Vigem.VigemDevice.IsAvailable()
   at XOutput.UI.Windows.MainWindowViewModel.Initialize()
   at XOutput.UI.Windows.MainWindow.<WindowLoaded>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

**Comment by csutorasa** [comment]
I am not sure how this can happen. The `vigemclient.dll`, that is missing, is added to the `XOutput.exe` file. Can you tell me which version is affected, and try some other versions if they work.

**Comment by totallymagical** [comment]
Well whatever the problem was it seems to have been resolved by redownloading the latest release, even though this problem was also with the latest release.

**Comment by csutorasa** [comment]
That may be a download, unzip or disk issue. If you face the issue again, reopen this issue.

**Comment by vdiorio** [comment]
I'm having the same issue, i've tried download other versions and they all come with the same problem. I've tried downloading it with other navigators and unziping with other softwares, but the problom persists

**Comment by vdiorio** [comment]
2019-05-08 15:18:13.663 -03:00 INFO  LanguageManager.set_Language: Language is set to English
2019-05-08 15:18:13.667 -03:00 INFO  MainWindowViewModel.Initialize: Loading settings was successful.
2019-05-08 15:18:13.684 -03:00 ERROR MainWindowViewModel.UnhandledException: System.DllNotFoundException: Não é possível carregar a DLL 'vigemclient.dll': Não foi possível encontrar o módulo especificado. (Exceção de HRESULT: 0x8007007E)
   em Nefarius.ViGEm.Client.ViGEmClient.vigem_alloc()
   em Nefarius.ViGEm.Client.ViGEmClient..ctor()
   em XOutput.Devices.XInput.Vigem.VigemDevice.IsAvailable()
   em XOutput.UI.Windows.MainWindowViewModel.Initialize()
   em XOutput.UI.Windows.MainWindow.<WindowLoaded>d__7.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
here's the log
