### ISSUE TITLE
it crashes at launch

### ISSUE THREAD

**Issue by J-K-Tech** [csutorasa/XOutput#573]
```
2022-03-15 18:50:43.332 -07:00 INFO  XOutput.Tools.DependencyEmbedder.CurrentDomain_AssemblyResolve: Loading SharpDX.DirectInput.dll from embedded resources
2022-03-15 18:50:43.402 -07:00 INFO  XOutput.Tools.DependencyEmbedder.CurrentDomain_AssemblyResolve: Loading SharpDX.dll from embedded resources
2022-03-15 18:50:43.525 -07:00 INFO  XOutput.UI.Windows.MainWindow..ctor: Starting XOutput in normal window
2022-03-15 18:50:43.662 -07:00 INFO  XOutput.Tools.DependencyEmbedder.CurrentDomain_AssemblyResolve: Loading Hardcodet.Wpf.TaskbarNotification.dll from embedded resources
2022-03-15 18:50:44.811 -07:00 INFO  XOutput.Tools.DependencyEmbedder.CurrentDomain_AssemblyResolve: Loading Newtonsoft.Json.dll from embedded resources
2022-03-15 18:50:44.847 -07:00 ERROR XOutput.App.Application_Startup: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'XOutput.Tools.LanguageManager' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Newtonsoft.Json.Utilities.ConvertUtils' threw an exception. ---> System.IO.FileNotFoundException
   at Newtonsoft.Json.Utilities.ConvertUtils..cctor()
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode(Type t, Boolean& isEnum)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.IsJsonPrimitiveType(Type t)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at XOutput.Tools.LanguageManager..ctor()
   at XOutput.Tools.LanguageManager..cctor()
   --- End of inner exception stack trace ---
   at XOutput.UI.Windows.MainWindowViewModel.Initialize(Action`1 log)
   at XOutput.UI.Windows.MainWindow..ctor(MainWindowViewModel viewModel, ArgumentParser argumentParser)
   at XOutput.UI.UIConfiguration.GetMainWindow(MainWindowViewModel viewModel, ArgumentParser argumentParser)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at XOutput.Tools.Resolver.Create(Object[] values)
   at XOutput.Tools.ApplicationContext.Resolve[T]()
   at XOutput.App.Application_Startup(Object sender, StartupEventArgs e)
2022-03-15 18:51:53.034 -07:00 ERROR XOutput.App.UnhandledException: System.NullReferenceException: Object reference not set to an instance of an object.
   at XOutput.UI.Windows.MainWindow.WindowClosing(Object sender, CancelEventArgs e)
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by requeijaum** [comment]
Same situation here:

```
2022-10-15 12:39:44.279 -03:00 INFO  XOutput.Tools.DependencyEmbedder.CurrentDomain_AssemblyResolve: Loading SharpDX.DirectInput.dll from embedded resources
2022-10-15 12:39:44.336 -03:00 INFO  XOutput.Tools.DependencyEmbedder.CurrentDomain_AssemblyResolve: Loading SharpDX.dll from embedded resources
2022-10-15 12:39:44.493 -03:00 ERROR XOutput.App.Application_Startup: System.Reflection.TargetInvocationException: Uma exceção foi acionada pelo destino de uma chamada. ---> System.TypeInitializationException: O inicializador de tipo de 'System.Windows.Window' acionou uma exceção. ---> System.TypeInitializationException: O inicializador de tipo de 'System.Windows.FrameworkElement' acionou uma exceção. ---> System.TypeInitializationException: O inicializador de tipo de 'System.Windows.UIElement' acionou uma exceção. ---> System.BadImageFormatException: Não foi possível carregar arquivo ou assembly 'UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ou uma de suas dependências. O módulo deveria conter um manifesto de assembly.
   em System.Windows.UIElement.RegisterEvents(Type type)
   em System.Windows.UIElement..cctor()
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Windows.FrameworkElement..cctor()
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Windows.Window..cctor()
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Windows.Window..ctor()
   em XOutput.UI.Windows.MainWindow..ctor(MainWindowViewModel viewModel, ArgumentParser argumentParser)
   em XOutput.UI.UIConfiguration.GetMainWindow(MainWindowViewModel viewModel, ArgumentParser argumentParser)
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   em System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   em System.Delegate.DynamicInvokeImpl(Object[] args)
   em XOutput.Tools.Resolver.Create(Object[] values)
   em XOutput.Tools.ApplicationContext.Resolve[T]()
   em XOutput.App.Application_Startup(Object sender, StartupEventArgs e)
```
